### ISSUE TITLE
Suggestion to add more customization

### ISSUE THREAD

**Issue by Osamu01** [adhansen/wilderness-player-alarm#11]
I was thinking it would be nice to disable the flashing screen since I have a verbal indicator (TTS + alarm notification), also to be able to choose whether to only alert for skulled players or not. I find that both options would be very useful.

**Comment by Osamu01** [comment]
this would also be in line with filters like "filter by level range" etc.

**Comment by adhansen** [comment]
Filter by level/skull is not allowed. Hotkey silence would be a nice feature though. Is this still necessary after timeout was added?

**Comment by adhansen** [comment]
Notification override integration (#28 ec5ad85) should cover the audio indicator feature request here. Since the rest is not allowed I'm going to close the issue.
