### ISSUE TITLE
 Enhancement: Allow separate colour flash for skulled enemies

### ISSUE THREAD

**Issue by APKiwi** [adhansen/wilderness-player-alarm#13]
Would be very helpful for determining pkers/pvmers

**Comment by adhansen** [comment]
This was in my initial request to the plug-in hub, but not added. The client offers no way to get the skull status of other players https://github.com/runelite/plugin-hub/pull/4036#issuecomment-1474484717
Possibly for PVP integrity reasons. I don't see this being allowed.
