### ISSUE TITLE
Option to disable alarm after X seconds

### ISSUE THREAD

**Issue by Z7-z** [adhansen/wilderness-player-alarm#2]
Currently it just stays on indefinitely, there are many occasions where a player appearing will just be a bot or another vulnerable player just tryna do his thing, and the alarm will trigger. An option for the alarm to turn off after X seconds would be really nice

**Comment by adhansen** [comment]
That makes a lot of sense, and could make it less annoying if another scout decides to just hang out next to you.
I'm wondering too if it should remember who triggered the alarm and only re-alarm only when someone else enters the range, but not if the first person leaves and comes back. Hmm...

**Comment by Z7-z** [comment]
That would be another great option I would definitely have that as a toggle however, PKers try to trick you and especially during the new wildy bosses there are people running through that you believe to be innocent and 5 seconds later a Chad PKer comes and that previous account is stood next to it, or the 2nd time the account runs through he'll try to voidwaker spec you while you've lost a bit of HP, in this instance the alarm wouldn't trigger since it's seen the account before. Would be a great option in general though for doing prayer training when you're amidst the bots, it wouldn't trigger everytime then

**Comment by Duplic1ty** [comment]
> That would be another great option I would definitely have that as a toggle however, PKers try to trick you and especially during the new wildy bosses there are people running through that you believe to be innocent and 5 seconds later a Chad PKer comes and that previous account is stood next to it, or the 2nd time the account runs through he'll try to voidwaker spec you while you've lost a bit of HP, in this instance the alarm wouldn't trigger since it's seen the account before. Would be a great option in general though for doing prayer training when you're amidst the bots, it wouldn't trigger everytime then

Yeah this is def valid - I would say if it's not too much work it would be sick to be able to display recent scouted players and to be able to whitelist certain names - the use case being scouting outside of callisto on an alt - I'm not in my main's clan and wont have any of the players added but they're not unfriendly

**Comment by adhansen** [comment]
> Yeah this is def valid - I would say if it's not too much work it would be sick to be able to display recent scouted players and to be able to whitelist certain names - the use case being scouting outside of callisto on an alt - I'm not in my main's clan and wont have any of the players added but they're not unfriendly

It's more a matter of breaking the rules than the difficulty. My pitch for this being legal to add to the plugin hub is predicated on the plugin 'not doing more than Player Indicators already does, but more visual' so I'm not so sure about things like allow-list, or saving recently-seen players, alarming based on combat level, etc.

Alarm duration by itself should be OK though.

**Comment by Duplic1ty** [comment]
Fair enough - amazing plugin either way :)

**Comment by Z7-z** [comment]
> > Yeah this is def valid - I would say if it's not too much work it would be sick to be able to display recent scouted players and to be able to whitelist certain names - the use case being scouting outside of callisto on an alt - I'm not in my main's clan and wont have any of the players added but they're not unfriendly
> 
> It's more a matter of breaking the rules than the difficulty. My pitch for this being legal to add to the plugin hub is predicated on the plugin 'not doing more than Player Indicators already does, but more visual' so I'm not so sure about things like allow-list, or saving recently-seen players, alarming based on combat level, etc.
> 
> Alarm duration by itself should be OK though.

what duplic1ty suggested I think is allowed since with player indicators you can toggle whether it shows for friends, clan mates, party members, team members, etc. So you could 'whitelist' names in the form of just adding them and toggling off the friends indicator, perhaps there is a way this gets abused but it's allowed on the hub, certainly helps the mere peasant players forced into wildy for drops & clues like myself

**Comment by adhansen** [comment]
I've poked around on the RuneLite discord recently and it turns out that anything that automates tracking other player information is a pretty big no-no, and I believe that would be necessary for 'disable alarm after X seconds': some internal state tracking who has triggered your alarm.
>  So you could 'whitelist' names in the form of just adding them and toggling off the friends indicator

This I like very much, it's manual enough that it wouldn't break the rules. Furthermore, autocompleting the names of nearby players like in the high-scores lookup should make it a little more usable for things like chaos altar where you're hanging around the same peeps for a while. Shall this be the path forward then?

I'm going out of town for a week but I'll add this and anything else that may come up (the plug-in is very new, so I'd expect some more issues) when I'm back in April. I probably won't PR a new version into the plugin hub for a few weeks though to get enough for a significant batch of changes at once and be mindful of the admins' time.

**Comment by adhansen** [comment]
Rule-breaking, won't implement.

**Comment by Z7-z** [comment]
how very unfortunate. thank you for checking out my idea at least
