### ISSUE TITLE
Don't trigger from players inside Ferox while you're outside

### ISSUE THREAD

**Issue by SirJorb** [adhansen/wilderness-player-alarm#25]
Currently, the plugin doesn't alert you of other players while you're in a safe area like Ferox Enclave, which makes sense. What makes less sense is it suddenly flashing the moment you step outside because of those same players still afk splashing inside Ferox. Is there any way we can make it so they aren't counted?

**Comment by adhansen** [comment]
Good catch, thanks for reporting. I'm sure this also applies to people on the other side of the wilderness ditch (or any other wilderness boundary).

**Comment by adhansen** [comment]
Done in f881c9e for version 2.0.0
