### ISSUE TITLE
Add an option to allow the alert to work anywhere

### ISSUE THREAD

**Issue by EricsPixels** [adhansen/wilderness-player-alarm#26]
I'd like the option for this plugin to work anywhere throughout the game, not just the wilderness. Would be good for DMM when it's released again in the summer.

**Comment by DapperMickie** [comment]
@EricsPixels If you mean you want this to work whenever you're in an area that has pvp enabled (either pvp world or dmm world), you can turn on the "Pvp world alerts". That should do it.
