### ISSUE TITLE
Feature Request: Compatibility with notification overrides

### ISSUE THREAD

**Issue by evilgenious448** [adhansen/wilderness-player-alarm#28]
Runelite recently added notification overrides. I know that the plugin already has some customisation that can make it behave separately from notifications, but it would be cool if this feature was enabled for even more customisation.

> Notification overrides
> Most client notifications can now have their notification style configured per-notification. Compatible notifications will have a cog icon next to the checkbox when enabled which opens the per-notification settings. Notifications without customized settings continue to use the default notification settings found in the RuneLite Notification Settings configuration section.
> 
> ![image](https://github.com/adhansen/plugin-repo/assets/32331499/b5246ab8-432e-4a5e-b7d7-ddf6c9508165)
> ![image](https://github.com/adhansen/plugin-repo/assets/32331499/96a38edf-2753-45b9-979e-a97e372a8779)

https://runelite.net/blog/show/2024-04-17-1.10.27-Release

**Comment by adhansen** [comment]
ec5ad85
