### ISSUE TITLE
Feature Request: Custom Audio

### ISSUE THREAD

**Issue by evilgenious448** [adhansen/wilderness-player-alarm#29]
Would you be able to implement custom audio to trigger when the alarm goes off. Would be great if we could link to a file path on our PC or web url of an mp3 file.

I like to use the alarm on a scout and would prefer to have that client minimised with the audio triggering if possible.

Either this or my other feature request (notification overrides) would be an awesome addition, either one would provide audio.

**Comment by adhansen** [comment]
I think if adding a sound I would prefer to use one of the existing game assets such as in:
https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/metronome/MetronomePlugin.java#L87

I haven't checked the notification overrides sound options but that might be the way to go here.

**Comment by evilgenious448** [comment]
I think a default sound to be played would be a great addition, but the ideal user experience is for users to be able to link a file path to the sound of their choice.

However, this functionality along with more robust notification options was made available in the latest version of Runelite and I believe @DapperMickie has made a PR that makes your plugin compatible with this.

**Comment by adhansen** [comment]
Opted with the route of implementing #28 (ec5ad85)
