### ISSUE TITLE
Sound and/or notification alert

### ISSUE THREAD

**Issue by LexieLamb** [adhansen/wilderness-player-alarm#3]
It would be great to have an option to either have a sound play and/or trigger an OS notification in addition to the flashing screen, in case a user is AFK

**Comment by albertofp** [comment]
New to Java and more specifically RL plugins but will be trying my hand at this very soon, seems like a simple enough feature to add.  I'm thinking a separate toggle for a OS notification and a sound

**Comment by albertofp** [comment]
Any specific sound you would recommend? Ideally want to have a default sound file and maybe the option to choose a custom one in some way (local or pointing to an URL)

**Comment by LexieLamb** [comment]
Well if I were to customize my own sound, I would probably pick something like a fire alarm sound, e.g. https://freesound.org/people/melokacool/sounds/613651/ . But I'm not sure if that would be too jarring for a default sound

**Comment by adhansen** [comment]
Desktop notification is in for the next release. I'll see about adding a sound as well.
