### ISSUE TITLE
[Feature Request] Improve support for DMM

### ISSUE THREAD

**Issue by Kevin-Chant** [adhansen/wilderness-player-alarm#33]
I recently started using this plugin on w345 and while it does work with "Pvp world alerts enabled", it doesn't respect safezones. Ideally if you have Pvp world alerts on and are on a deadman world the plugin would only alert if you're not in a guarded area.

**Comment by adhansen** [comment]
I've sketched out an outline for how this can be done with a safezone around Ferox on branch WildernessPlayerAlarm/25 to address #25. But for starters this will only include Ferox Enclave.
I want to be careful about expanding this because respecting safezones involves tracing out an area and checking if players are within the boundary, like so:

![image](https://github.com/adhansen/plugin-repo/assets/26663184/93d88e4c-66a1-4c61-89f1-89dc9724be59)

Meaning, in a place like the GE on DMM worlds with a high density of players it will be no small amount of computation _each tick_ to check if each player is within the safezone.

**Comment by Kevin-Chant** [comment]
>  I want to be careful about expanding this because respecting safezones involves tracing out an area and checking if players are within the boundary, like so:

Oh, yeah if that's the approach then that seems really annoying to implement. Does Runelite's API expose the info the client uses to render the "Guarded"/"Deadman" icon under the minimap? I would've hoped it was a simple varbit lookup or similar to see whether you're currently in a safezone.

Also, in case it helps, I would assume that just checking whether you yourself are in a safezone or not is good enough. If a player is in a safezone that you're on the outside of, I would still think it's worth notifying for.

**Comment by adhansen** [comment]
> Also, in case it helps, I would assume that just checking whether you yourself are in a safezone or not is good enough

Good point, there's no need to check other players in this case. I think the way to do this is to identify the flag that tells you whether or not you're in a safezone in DMM and block the alarm from going off when it is set. I don't see why this should have a config option either.

**Comment by Kevin-Chant** [comment]
> identify the flag that tells you whether or not you're in a safezone in DMM and block the alarm from going off when it is set

Yep this is exactly what I had in mind when filing this request. I would try to do it myself but I'm not well practiced with Java and don't know how to find the flag. Really appreciate you being open to requests like this though; this plugin is a gamechanger for DMM!

**Comment by adhansen** [comment]
Thanks for brainstorming this @Kevin-Chant 
I pushed this functionality to the release branch and also included it in the open PR into the plugin hub:
https://github.com/runelite/plugin-hub/pull/6239
No guarantees that this will be live in time for seasonal DMM but it should come with the next update.

**Comment by Kevin-Chant** [comment]
Thanks a bunch for making this happen! Your plugin has already been saving me on permanent dmm and this will make it even more useful :)

**Comment by Kevin-Chant** [comment]
Hey just wanted to jump back in here and say again - this addition has been absolutely amazing! It's working perfectly in both permanent and seasonal DMM and now I can leave it on at all times without having my screen flashing at me at the GE.
@adhansen you and everyone else who makes these plugins for the community are a huge part of what makes this game great <3
