### ISSUE TITLE
Flashing/Menu issue

### ISSUE THREAD

**Issue by Disease40** [adhansen/wilderness-player-alarm#38]
![Osrs issue](https://github.com/adhansen/plugin-repo/assets/175343820/7516afb8-62dc-4208-bbf3-9f9ef7032e27)
I am having a problem where my alt account here isn't recieving the flashing when someone arrives, I noticed that on my account I am using in the wilderness I am seeing a "timeout" and "Flash color" bar. Which this one isn't showing. 

   Not sure what is wrong

**Comment by Dorchmund** [comment]
I am having the same issue, anyone knows how to solve this? It was working for me, i was running to artio cave and it was working, and suddenly it a pker came in and it didnt go off, cant solve it

**Comment by adhansen** [comment]
A lot of the notification functionality was refactored into a native RuneLite customizable notification with the last update. The flash settings are under the cog by "Notification":

![image](https://github.com/user-attachments/assets/cdead415-158a-486a-bb8f-cc4b0727a204)


![image](https://github.com/user-attachments/assets/fe63eeb3-025a-4482-a96c-ff4b196fbbf0)

**Comment by adhansen** [comment]
This change has been rolled back
