### ISSUE TITLE
Custom ignore list

### ISSUE THREAD

**Issue by post-async** [adhansen/wilderness-player-alarm#44]
add a way to ignore specific rsns without needing to add them to friends or ignore them

if you don't want to ignore someone and their private is off, there is no way to turn notifications off for them. comma separated text box that u can put rsns in would make this easy. 

(i can write the code for this, but only if you would accept the PR. let me know)

**Comment by adhansen** [comment]
That's reasonable enough, I'd like to do it myself though

**Comment by adhansen** [comment]
Done in 2cefd2d0b773d153202ee76594bd9bbcdc85ce3a
