### ISSUE TITLE
Enhancement: ability to disable the flash functionality

### ISSUE THREAD

**Issue by Duplic1ty** [adhansen/wilderness-player-alarm#8]
Now that we have the desktop notification it would be awesome to actually be able to toggle the flash screen functionality - particularly a few friends I have said they like the alert but dislike the flashing screen (or inability to set a flash timer)

**Comment by mikehoyle** [comment]
You should be able to set the flash color to fully transparent in the config -- I imagine that'd have the same effect.

**Comment by Duplic1ty** [comment]
> You should be able to set the flash color to fully transparent in the config -- I imagine that'd have the same effect.

You're right - 0000FF00 seems to work
